### ISSUE TITLE
test output insufficient when running learn

### ISSUE THREAD

**Issue by d-d-d-dalia** [learn-co-curriculum/js-dom-and-events-hide-and-seek-lab#5]
I don't know if this is a recurring issue or not, but I had a student today who wasn't getting any details in the test output when running learn (student is using VS code and terminal on iOS). We ran it in the browser however, and then were able to see more detailed test failures by running `mocha.run()` in the chrome dev tools console.

**Comment by maxwellbenton** [comment]
Hi @d-d-d-dalia,

Sometimes this can happen if node/npm versions are out of date. I'm not sure what may have caused this, but I have updated this lesson's package.json and changed the test output to clearly display each test's title rather than Nyan cat, so this problem should not occur again. 

Thank you for bringing this to our attention!
